### ISSUE TITLE
A Problem on Sticks (TREE2) 

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/100DaysofCP#1]

**Comment by rasacharjee** [comment]
Can you assign this issue to me

**Comment by aryamasinha** [comment]
Sure

**Comment by rasacharjee** [comment]
Thanks @aryamasinha for assigning the issue. I have opened a pull request along with the screen shot of the solution proposed and solution accepted. Can you please look into the same. I would be grateful if the pull request is merged.
