### ISSUE TITLE
Chef and Proxy(PROXYC)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/100DaysofCP#10]

**Comment by Pulkitmahajan01** [comment]
Hi @aryamasinha ,Could you please assign me this issue.

**Comment by Pulkitmahajan01** [comment]
As i was assigned this issue, i have made a pr too. I would be grateful to you if you merge my pr and consider it for hacktoberfest2020

**Comment by aryamasinha** [comment]
Sure :)
