### ISSUE TITLE
Minimum Maximum (MNMX)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/100DaysofCP#34]

**Comment by Satvik-B** [comment]
@aryamasinha would like to work on this please assign

**Comment by jhoserpacheco** [comment]
I would like to collaborate, assign me

**Comment by shrishtrip** [comment]
Can I work on this issue?

**Comment by ajitg1** [comment]
@aryamasinha I would like to work on this, assign me.

**Comment by sanchit28** [comment]
Can I work on this issue? Assign me
