### ISSUE TITLE
Longest Weird Subsequence (LWS)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/100DaysofCP#38]

**Comment by khushboogupta13** [comment]
Hi, can I contribute towards this issue?

**Comment by khushboogupta13** [comment]
I have added my code, please do accept it.

**Comment by kokilgupta** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/63225401/94768860-37d84a00-03ce-11eb-8511-89ca3f32666d.png)

I have added my code
