### ISSUE TITLE
Eugene and function (KFUNC)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/100DaysofCP#39]

**Comment by cenation007** [comment]
Hey @aryamasinha I would love to solve this issue. Could you please assign me this?

**Comment by abhishekraj272** [comment]
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04

**Comment by abhishekraj272** [comment]
Please add my blog to your repo.
