### ISSUE TITLE
Is the repo taking PRs ?

### ISSUE THREAD

**Issue by silentWatcher3** [aryamasinha/100DaysofCP#6]
And if yes, these are codechef problems? Or some other platforms ?

**Comment by aryamasinha** [comment]
Yes , these are codechef practice problems and yes , we are taking prs. I would like you to solve the question (mentioned in the issue) first on the codechef platform first and then after successful submission , create a folder with your name in the First_Contributions folder and put the code there.

Also , happy coding :)
